# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Piccy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Piccy
  pod 'Parse'
  pod 'AFNetworking'
  target 'PiccyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiccyUITests' do
    # Pods for testing
  end

end
